//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fees_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_information_parameter_translation
    {
        public int account_info_non_trans_id { get; set; }
        public int language_id { get; set; }
        public string parameter { get; set; }
    
        public virtual account_information_parameter account_information_parameter { get; set; }
        public virtual language_table language_table { get; set; }
    }
}
