//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fees_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_parameter_values
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account_parameter_values()
        {
            this.account_parameter_values_translation = new HashSet<account_parameter_values_translation>();
        }
    
        public int id { get; set; }
        public int currency_id { get; set; }
        public int parameter_id { get; set; }
    
        public virtual account_information_parameter account_information_parameter { get; set; }
        public virtual bank_currency_table bank_currency_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account_parameter_values_translation> account_parameter_values_translation { get; set; }
    }
}
