//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fees_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class dormitories_table_translation
    {
        public int language_id { get; set; }
        public int dormitories_table_non_trans_id { get; set; }
        public string dormitory_name { get; set; }
        public string dormitory_address { get; set; }
        public string gender_allocation { get; set; }
        public string rooms_payment_period { get; set; }
    
        public virtual dormitories_table dormitories_table { get; set; }
        public virtual language_table language_table { get; set; }
    }
}
