//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fees_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class dormitory_type_translation
    {
        public int language_id { get; set; }
        public int dormitory_type_non_trans_id { get; set; }
        public string type_name { get; set; }
    
        public virtual dormitory_type dormitory_type { get; set; }
        public virtual language_table language_table { get; set; }
    }
}
