//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fees_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class facility_option_translation
    {
        public int facility_option_non_trans_id { get; set; }
        public int language_id { get; set; }
        public string facility_option { get; set; }
        public string facility_option_description { get; set; }
    
        public virtual facility_option facility_option1 { get; set; }
        public virtual language_table language_table { get; set; }
    }
}
