//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fees_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public room_table()
        {
            this.room_facility = new HashSet<room_facility>();
            this.room_table_translation = new HashSet<room_table_translation>();
        }
    
        public int id { get; set; }
        public int dormitory_id { get; set; }
        public string room_picture_url { get; set; }
        public double room_price { get; set; }
        public double room_price_installment { get; set; }
        public int room_area { get; set; }
    
        public virtual dormitories_table dormitories_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<room_facility> room_facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<room_table_translation> room_table_translation { get; set; }
    }
}
