//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fees_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_table_translation
    {
        public int language_id { get; set; }
        public int room_table_non_trans_id { get; set; }
        public string room_type { get; set; }
        public string room_title { get; set; }
    
        public virtual language_table language_table { get; set; }
        public virtual room_table room_table { get; set; }
    }
}
