//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fees_proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_facility
    {
        public int id { get; set; }
        public int facility_id { get; set; }
        public int room_id { get; set; }
        public Nullable<int> facility_option_id { get; set; }
    
        public virtual facility_table facility_table { get; set; }
        public virtual room_table room_table { get; set; }
    }
}
